 sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tyagiankur18/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tyagiankur18/docker-react npm run test